### ISSUE TITLE
Hi i am facing problem in apolloclient  config

### ISSUE THREAD

**Issue by gmchaturvedi1** [banterfm/graphql-crunch#12]
i am getting the following error:

Error: no value resolved
    at Object.complete (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:695191)
    at complete (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:376930)
    at t.s (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:673115)
    at t.n.emit (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:307830)
    at chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:381756

please suggest.

Thanks & Regards
gmchaturvedi

**Comment by Natansab** [comment]
@gmchaturvedi1 I am facing the same issue, did you fix it?

**Comment by gmchaturvedi1** [comment]
no still waiting for someone from lib will reply

**Comment by acomito** [comment]
Seeing this as well, but not using graphql-crunch

**Comment by stevekrenzel** [comment]
Hey all, lib author here. That issue doesn't appear to have anything to do with `graphql-crunch`. Looks like it's related to a Chrome extension.
